config/routes.rb
Rails.application.routes.draw do
  devise_for :athletes, controllers: { registrations: "registrations" }
  resources :wods

  resources :movements
  resources :athletes

  root to: "athletes#index"

end

app/models/wod.rb
class Wod < ActiveRecord::Base

  belongs_to :athlete
  has_many :wod_movements
  has_many :movements, through: :wod_movements

  def possible_movements
    Movement.all
  end
end

app/controllers/wods_controller.rb
class WodsController < ApplicationController
  before_action :authenticate_athlete!
  before_action :set_wod, only: [:show, :edit, :update, :destroy]

  # GET /wods
  # GET /wods.json
  def index
    @wods = Wod.all
  end

  # GET /wods/1
  # GET /wods/1.json
  def show
    @wods = Wod.where(athlete_id: current_athlete.id)
    @athlete = Wod.find(params[:id]).athlete

    end

    # GET /wods/new
    def new
      @wod = Wod.new
      @wod_movement = @wod.wod_movements.build

    end

    # GET /wods/1/edit
    def edit
    end

    # POST /wods
    # POST /wods.json
    def create
      @wod = Wod.new(wod_params)
      movements = Movement.where(id:params[:movements][:id])
      params[:movements][:id].each do |movement|
        if !movement.empty?
          @wod.wod_movements.build(:movement_id => movement)
        end
      end

      respond_to do |format|
        if @wod.save
          format.html { redirect_to @wod, notice: 'Wod was successfully created.' }
          format.json { render :show, status: :created, location: @wod }
        else
          format.html { render :new }
          format.json { render json: @wod.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /wods/1
    # PATCH/PUT /wods/1.json
    def update
      respond_to do |format|
        if @wod.update(wod_params)
          format.html { redirect_to @wod, notice: 'Wod was successfully updated.' }
          format.json { render :show, status: :ok, location: @wod }
        else
          format.html { render :edit }
          format.json { render json: @wod.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /wods/1
    # DELETE /wods/1.json
    def destroy
      @wod.destroy
      respond_to do |format|
        format.html { redirect_to wods_url, notice: 'Wod was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_wod
      @wod = Wod.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wod_params
      params.require(:wod).permit(:athlete_id, :pr, :score, :benchmark)
    end
  end

app/helpers/wods_helper.rb
module WodsHelper
end

app/views/wods/_form.html.erb
<% wod ||= @wod %>

<%= form_for(wod) do |f| %>
  <% if wod.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wod.errors.count, "error") %> prohibited this wod from being saved:</h2>

      <ul>
      <% wod.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.hidden_field :athlete_id %>
    <%= f.fields_for(:movements, ) do |wm| %>
    <div class="field">
     <%= wm.label "List of Movements" %><br>
      <%= collection_select(:movements, :id, wod.possible_movements, :id, :name, {}, {:multiple =>  true}) %>
    </div>

  <% end %>

  <div class="field">
    <%= f.label :score %><br>
    <%= f.text_field :score %>
  </div>

  <div class="field">
    <%= f.label :pr %><br>
    <%= f.check_box :pr %>
  </div>

  <div class="field">
    <%= f.label :benchmark %><br>
    <%= f.check_box :benchmark %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wods/edit.html.erb
<h1>Editing wod</h1>

<%= render 'form' %>

app/views/wods/index.html.erb
<h1>Listing wods</h1>

<table>
  <thead>
    <tr>
      <th>Pr</th>
      <th>Score</th>
      <th>Benchmark</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wods.each do |wod| %>
      <tr>
        <td><%= wod.pr %></td>
        <td><%= wod.score %></td>
        <td><%= wod.benchmark %></td>
        <td><%= link_to 'Show', wod %></td>
        <td><%= link_to 'Edit', edit_wod_path(wod) %></td>
        <td><%= link_to 'Destroy', wod, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wod', new_wod_path %>

app/views/wods/new.html.erb
<h1>New wod</h1>

<%= render 'form' %>

<%= link_to 'Back', wods_path %>

app/views/wods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <% @wod.movements.each do |mov| %>
      <td><%= mov.name %></td>
    <% end %>
</p>

<p>
  <strong>Score:</strong>
  <%= @wod.score %>
</p>

<p>
  <strong>Pr:</strong>
  <%= @wod.pr %>
</p>

<p>
  <strong>Benchmark:</strong>
  <%= @wod.benchmark %>
</p>




<%= link_to 'Edit', edit_wod_path(@wod) %> |
<%= link_to 'Back to your Profile', athlete_path(@athlete)%>