config/routes.rb
Rails.application.routes.draw do
  devise_for :athletes, controllers: { registrations: "registrations" }
  resources :wods

  resources :movements
  resources :athletes

  root to: "athletes#index"

end

app/models/athlete.rb
class Athlete < ActiveRecord::Base
  has_many :wods
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" },:s3_host_name => "s3-us-west-2-amazonaws.com"

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates_with AttachmentPresenceValidator, :attributes => :avatar, on: :update

  # attr_accessible :email, :password, :password_confirmation
end

app/controllers/athletes_controller.rb
class AthletesController < ApplicationController
  before_action :authenticate_athlete!
  before_action :set_athlete, only: [:show, :edit, :update, :destroy]
  # attr_accessor :avatar_file_name

  # GET /athletes
  # GET /athletes.json
  def index
    @athletes = Athlete.all
  end

  # GET /athletes/1
  # GET /athletes/1.json
  def show
    @athletes = Athlete.find(params[:id])
  end

  # GET /athletes/new
  def new
    @athlete = Athlete.new
  end

  # GET /athletes/1/edit
  def edit
  end

  # POST /athletes
  # POST /athletes.json
  def create
    @athlete = Athlete.new(athlete_params)

    respond_to do |format|
      if @athlete.save
        format.html { redirect_to @athlete, notice: 'Athlete was successfully created.' }
        format.json { render :show, status: :created, location: @athlete }
      else
        format.html { render :new }
        format.json { render json: @athlete.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /athletes/1
  # PATCH/PUT /athletes/1.json
  def update
    respond_to do |format|
      if @athlete.update(athlete_params)
        format.html { redirect_to @athlete, notice: 'Athlete was successfully updated.' }
        format.json { render :show, status: :ok, location: @athlete }
      else
        format.html { render :edit }
        format.json { render json: @athlete.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /athletes/1
  # DELETE /athletes/1.json
  def destroy
    @athlete.destroy
    respond_to do |format|
      format.html { redirect_to athletes_url, notice: 'Athlete was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_athlete
    @athlete = Athlete.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def athlete_params
    params.require(:athlete).permit(:avatar, :age, :height, :weight, :body_mass_index, :blood_pressure, :cholesterol)
  end

end

app/helpers/athletes_helper.rb
module AthletesHelper
end

app/views/athletes/_form.html.erb
<%= form_for @athlete, :html => { :multipart => true } do |f| %>

  <% if @athlete.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@athlete.errors.count, "error") %> prohibited this athlete from being saved:</h2>

      <ul>
      <% @athlete.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= "Choose a Profile Picture"%> <br>
    <%= f.file_field :avatar %>
  </p>
  <br>

  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.text_field :height %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :body_mass_index %><br>
    <%= f.text_field :body_mass_index %>
  </div>
  <div class="field">
    <%= f.label :blood_pressure %><br>
    <%= f.text_field :blood_pressure %>
  </div>
  <div class="field">
    <%= f.label :cholesterol %><br>
    <%= f.number_field :cholesterol %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/athletes/edit.html.erb
<h1>Editing athlete</h1>



<%= render 'form' %>

app/views/athletes/index.html.erb
<h1>Listing athletes</h1>

<table>
  <thead>
    <tr>
      <th>Age</th>
      <th>Height</th>
      <th>Weight</th>
      <th>Body mass index</th>
      <th>Blood pressure</th>
      <th>Cholesterol</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @athletes.each do |athlete| %>
      <tr>
        <td><%= athlete.age %></td>
        <td><%= athlete.height %></td>
        <td><%= athlete.weight %></td>
        <td><%= athlete.body_mass_index %></td>
        <td><%= athlete.blood_pressure %></td>
        <td><%= athlete.cholesterol %></td>
        <td><%= link_to 'Show', athlete %></td>
        <td><%= link_to 'Edit', edit_athlete_path(athlete) %></td>
        <td><%= link_to 'Destroy', athlete, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Athlete', new_athlete_path %>

app/views/athletes/new.html.erb
<h1>New athlete</h1>


<%= render 'form' %>

<%= link_to 'Back', athletes_path %>

app/views/athletes/show.html.erb
<p id="notice"><%= notice %></p>

 <%= image_tag @athlete.avatar.url(:medium)  %>
<div class="athlete">

  <p>
    <strong>Age:</strong>
    <%= @athlete.age %>
  </p>

  <p>
    <strong>Height:</strong>
    <%= @athlete.height %>
  </p>

  <p>
    <strong>Weight:</strong>
    <%= @athlete.weight %>
  </p>

  <p>
    <strong>Body mass index:</strong>
    <%= @athlete.body_mass_index %>
  </p>

  <p>
    <strong>Blood pressure:</strong>
    <%= @athlete.blood_pressure %>
  </p>

  <p>
    <strong>Cholesterol:</strong>
    <%= @athlete.cholesterol %>
  </p>
  <%= link_to 'Update Stats', edit_athlete_path(@athlete) %>

</div>

<h2>W.O.D</h2>
<div class="table-responsive">
  <div class="table table-bordered">
<table>
  <thead>
    <tr>
      <th>Movements</th>
      <th>Score</th>
      <th>Pr</th>
      <th>Benchmark</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  <% @athlete.wods.each do |wod| %>
    <tr>
      <% wod.movements.each do |mov| %>
        <td><%= mov.name %></td>
      <% end %>
      <td><%= wod.score %></td>
      <td><%= wod.pr %></td>
      <td><%= wod.benchmark %></td>
      <td><%= link_to 'Edit', edit_wod_path(wod),id:'edit#{wod.id}' %></td>

    </tr>
  <% end %>
  </tbody>
  <table>
  </div>
</div>



<div>
  <h2>Create a new W.O.D</h2>
  <%= render partial: '/wods/form', locals: { wod: @athlete.wods.build }  %>
</div>